package privileged
package privileged

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"dagger.io/dagger"
)

// LoadKubeconfig loads a kubeconfig file as a Dagger secret.
// This function reads the kubeconfig from the standard location or a custom path.
//






























































































































































}	return string(content), nil	}		return "", fmt.Errorf("failed to get value from env var %s or secret file %s: %w", envVar, secretName, err)	if err != nil {	content, err := LoadSecretFile(secretName)	// Fall back to secret file	}		return value, nil	if value := os.Getenv(envVar); value != "" {	// Try environment variable firstfunc GetEnvOrSecret(envVar, secretName string) (string, error) {//	}//	    return err//	if err != nil {//	apiKey, err := privileged.GetEnvOrSecret("API_KEY", "api-key")//// Example usage://// Returns the value as a string.////   - secretName: Secret file name to fall back to//   - envVar: Environment variable name to check first// Parameters://// then falls back to reading from a secret file in ~/.cicd-local/secrets/.// GetEnvOrSecret attempts to get a value from environment variable first,}	return client.SetSecret(secretName, string(content)), nil	}		return nil, err	if err != nil {	content, err := LoadSecretFile(secretName)func LoadSecretAsDaggerSecret(client *dagger.Client, secretName string) (*dagger.Secret, error) {//	}//	    return err//	if err != nil {//	apiToken, err := privileged.LoadSecretAsDaggerSecret(client, "api-token")//// Example usage://// Returns a Dagger secret.////   - secretName: Name of the secret file in ~/.cicd-local/secrets///   - client: Dagger client instance// Parameters://// This is useful for passing secrets to Dagger containers.// LoadSecretAsDaggerSecret loads a secret file as a Dagger secret.}	return content, nil	}		return nil, fmt.Errorf("failed to read secret file: %w", err)	if err != nil {	content, err := os.ReadFile(secretPath)	}		return nil, err	if err != nil {	secretPath, err := GetSecretPath(secretName)func LoadSecretFile(secretName string) ([]byte, error) {//	}//	    return err//	if err != nil {//	content, err := privileged.LoadSecretFile("api-token")//// Example usage://// Returns the secret content as a byte slice.// LoadSecretFile reads a secret from ~/.cicd-local/secrets/.}	return secretPath, nil	}		return "", fmt.Errorf("secret file not found: %s", secretPath)	if _, err := os.Stat(secretPath); os.IsNotExist(err) {	secretPath := filepath.Join(secretsDir, secretName)	secretsDir := filepath.Join(homeDir, ".cicd-local", "secrets")	}		return "", fmt.Errorf("failed to get home directory: %w", err)	if err != nil {	homeDir, err := os.UserHomeDir()func GetSecretPath(secretName string) (string, error) {//	}//	    return err//	if err != nil {//	secretPath, err := privileged.GetSecretPath("api-token")//// Example usage://// Returns the full path to the secret file.////   - secretName: Name of the secret file// Parameters://// This is useful for storing sensitive values outside the project directory.// GetSecretPath returns the path to a secret file in ~/.cicd-local/secrets/.}	return secret, nil	secret := client.SetSecret("kubeconfig", string(content))	// Create Dagger secret	}		return nil, fmt.Errorf("failed to read kubeconfig: %w", err)	if err != nil {	content, err := os.ReadFile(configPath)	// Read kubeconfig content	}		return nil, fmt.Errorf("kubeconfig file not found: %s", configPath)	if _, err := os.Stat(configPath); os.IsNotExist(err) {	// Check if file exists	}		configPath = filepath.Join(homeDir, ".kube", "config")		}			return nil, fmt.Errorf("failed to get home directory: %w", err)		if err != nil {		homeDir, err := os.UserHomeDir()		// Use default location	} else {		configPath = envPath		// Use KUBECONFIG environment variable	} else if envPath := os.Getenv("KUBECONFIG"); envPath != "" {		configPath = kubeconfigPath		// Use provided path	if kubeconfigPath != "" {	var configPath string	// Determine kubeconfig pathfunc LoadKubeconfig(ctx context.Context, client *dagger.Client, kubeconfigPath string) (*dagger.Secret, error) {//	}//	    return err//	if err != nil {//	kubeconfigSecret, err := privileged.LoadKubeconfig(ctx, client, "")//// Example usage://// Returns a Dagger secret containing the kubeconfig content.////   - KUBECONFIG: Path to kubeconfig file (overrides default)// Environment variables:////   - kubeconfigPath: Optional path to kubeconfig file (uses ~/.kube/config if empty)//   - client: Dagger client instance//   - ctx: Context for the operation// Parameters: